/* ------------------------ screen names ---------------------------------  */
export const OTP_URL = "otp";
export const LOGIN_URL = "login";
export const PERSONAL_INFO = "personalInfo";
export const PROFILE = "profile";
export const MAIN_BOTTOM = "main_bottom";
export const HOME = "home";
export const MY_POLICIES = "my_policy";
export const DISCOVER = "discover";
export const SUPPORT = "support";
export const CAR_INFO = "car_info";
export const ADD_ONS = "add_ons";
export const INSURANCE_USER_DETAILS = "insurance_user_details";
/* --------------------------------------------------------- */

/* ----------------------- data ---------------------------------- */

export const INSURANCE_OPTIONS = [
	{
		id: 1,
		title: "Car",
	},
	{
		id: 2,
		title: "Bike",
	},
	{
		id: 3,
		title: "Travel",
	},
	{
		id: 4,
		title: "Health",
	},
];

export const NEW_OPTIONS = [
	{
		id: 1,
		icon: "car",
		title: "New car insurance",
	},
	{
		id: 2,
		icon: "car-cog",
		title: "Upgrade your car",
	},
	{
		id: 3,
		icon: "car-info",
		title: "Vehicle info",
	},
	{
		id: 4,
		icon: "car-wrench",
		title: "Car Valuation",
	},
];

export const MAINTAIN_OPTIONS = [
	{
		id: 1,
		title: "Vehicle alerts",
		icon: "bell-alert",
	},
	{
		id: 2,
		title: "Pay traffic challans",
		icon: "traffic-light",
	},
	{
		id: 3,
		title: "Emission check",
		icon: "flower-pollen",
	},
	{
		id: 4,
		title: "Fuel prices",
		icon: "fuel",
	},
];

export const VEHICLES_RELATED = [
	{ id: 1, title: "Vehicle alerts", icon: "bell-alert" },
	{ id: 2, title: "Upgrade your car", icon: "car-2-plus" },
	{ id: 3, title: "Vehicle info", icon: "car-info" },
	{ id: 4, title: "Pay traffic challans", icon: "traffic-light" },
	{ id: 5, title: "Emission check", icon: "flower-pollen" },
	{ id: 6, title: "Fuel prices", icon: "fuel" },
	{ id: 7, title: "Car valuation", icon: "car" },
];

export const HELP_SUPPORT = [
	{
		id: 1,
		iconName: "pen",
		title: "Write to us",
		subtitle: "We will reply as soon as we can.",
		iconColor: "black",
	},
	{
		id: 2,
		iconName: "wechat",
		title: "Call us",
		subtitle: "Talk to us, we are here to help.",
		iconColor: "black",
	},
	{
		id: 3,
		iconName: "message",
		title: "FAQs",
		subtitle: "Find answers instantly.",
		iconColor: "black",
	},
];

export const EXPLORE_MORE = [
	{
		id: 1,
		iconName: "book-open-variant",
		title: "Guides",
		subtitle: "Read our guides on insurance.",
		iconColor: "black",
		iconSize: 50,
	},
	{
		id: 2,
		iconName: "tooltip-edit",
		title: "Articles",
		subtitle: "Helpful articles to keep you informed.",
		iconColor: "black",
		iconSize: 50,
	},
	{
		id: 3,
		iconName: "book-minus-multiple",
		title: "Ebooks",
		subtitle: "Grow your knowledge on all things insurance.",
		iconColor: "black",
		iconSize: 50,
	},
];

export const PROFILE_SECTION = [
	{
		id: 1,
		leftIcon: "account-circle-outline",
		title: "Personal info",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 2,
		leftIcon: "account-group-outline",
		title: "Family",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 3,
		leftIcon: "car-outline",
		title: "Vehicles",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 4,
		leftIcon: "google-maps",
		title: "Addresses",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 5,
		leftIcon: "bank-outline",
		title: "Payout methods",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	// {
	// 	id: 6,
	// 	leftIcon: "marker-check",
	// 	title: "KYC information",
	// 	rightIcon: "arrow-right-thin-circle-outline",
	// 	screen: PERSONAL_INFO,
	// },
	{
		id: 7,
		leftIcon: "card-bulleted-outline",
		title: "Saved cards",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 8,
		leftIcon: "bell",
		title: "Notifications",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 9,
		leftIcon: "cellphone-cog",
		title: "Support",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 10,
		leftIcon: "information-outline",
		title: "About us",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
	{
		id: 11,
		leftIcon: "book-edit-outline",
		title: "Privacy policy",
		rightIcon: "arrow-right-thin-circle-outline",
		screen: PERSONAL_INFO,
	},
];

export const CAR_DATA = [
	{
		license: "MH10CW5542",
		model_name: "HONDA SHINE",
		owner: "Owner 1",
		registration_date: "2015-01-12",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 1",
		owner_count: 4,
		insurance_date: "2022-07-14",
		pollution: "2020-04-27",
		model: "Maker 1/Model 1",
		insurer_name: "Insurer 1",
		vehicle_color: "Color 1",
		manufacturing_date: "1/1/2010",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "yf6vkrmwvpr",
		pucc_no: "MH05924450",
		puc_expiry: "2012-05-31",
		fit_upto: "2029-03-13",
	},
	{
		license: "TP06VE5W0S",
		owner: "Owner 2",
		registration_date: "2018-03-23",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 2",
		owner_count: 5,
		insurance_date: "2010-05-20",
		pollution: "2018-02-22",
		model: "Maker 2/Model 2",
		insurer_name: "Insurer 2",
		vehicle_color: "Color 2",
		manufacturing_date: "1/2/2011",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "4bz3iwrikzq",
		pucc_no: "MH07330237",
		puc_expiry: "2011-10-14",
		fit_upto: "2031-06-18",
	},
	{
		license: "RD7SD2TSXH",
		owner: "Owner 3",
		registration_date: "2011-11-19",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 3",
		owner_count: 5,
		insurance_date: "2016-06-23",
		pollution: "2012-11-28",
		model: "Maker 3/Model 3",
		insurer_name: "Insurer 3",
		vehicle_color: "Color 3",
		manufacturing_date: "1/3/2012",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "rm9xnca0dt",
		pucc_no: "MH07261023",
		puc_expiry: "2014-01-27",
		fit_upto: "2032-11-13",
	},
	{
		license: "C3G33MJBQG",
		owner: "Owner 4",
		registration_date: "2015-10-21",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 4",
		owner_count: 5,
		insurance_date: "2014-09-22",
		pollution: "2015-06-28",
		model: "Maker 4/Model 4",
		insurer_name: "Insurer 4",
		vehicle_color: "Color 4",
		manufacturing_date: "1/4/2013",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "98nuya8f5vw",
		pucc_no: "MH06862278",
		puc_expiry: "2016-11-10",
		fit_upto: "2029-05-22",
	},
	{
		license: "FN3E5EBN01",
		owner: "Owner 5",
		registration_date: "2010-03-20",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 5",
		owner_count: 1,
		insurance_date: "2019-09-09",
		pollution: "2016-12-23",
		model: "Maker 5/Model 5",
		insurer_name: "Insurer 5",
		vehicle_color: "Color 5",
		manufacturing_date: "1/5/2014",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "20lebg4sqqo",
		pucc_no: "MH04612231",
		puc_expiry: "2019-10-24",
		fit_upto: "2031-12-30",
	},
	{
		license: "YK1TMMZO9V",
		owner: "Owner 6",
		registration_date: "2021-06-10",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 6",
		owner_count: 2,
		insurance_date: "2017-01-26",
		pollution: "2020-07-17",
		model: "Maker 6/Model 6",
		insurer_name: "Insurer 6",
		vehicle_color: "Color 6",
		manufacturing_date: "1/6/2015",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "3znoj8hjw6",
		pucc_no: "MH05916566",
		puc_expiry: "2022-12-18",
		fit_upto: "2030-02-19",
	},
	{
		license: "S2TLUXB1J0",
		owner: "Owner 7",
		registration_date: "2020-01-16",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 7",
		owner_count: 1,
		insurance_date: "2017-03-09",
		pollution: "2012-08-24",
		model: "Maker 7/Model 7",
		insurer_name: "Insurer 7",
		vehicle_color: "Color 7",
		manufacturing_date: "1/7/2016",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "vj1q4bwh7hs",
		pucc_no: "MH02875856",
		puc_expiry: "2015-05-30",
		fit_upto: "2030-06-11",
	},
	{
		license: "9Z0YBAX1SY",
		owner: "Owner 8",
		registration_date: "2015-11-22",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 8",
		owner_count: 3,
		insurance_date: "2014-04-14",
		pollution: "2014-08-30",
		model: "Maker 8/Model 8",
		insurer_name: "Insurer 8",
		vehicle_color: "Color 8",
		manufacturing_date: "1/8/2017",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "68hr7rtu9ho",
		pucc_no: "MH04139954",
		puc_expiry: "2018-03-31",
		fit_upto: "2030-06-13",
	},
	{
		license: "AR6R85710N",
		owner: "Owner 9",
		registration_date: "2011-01-09",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 9",
		owner_count: 3,
		insurance_date: "2015-08-06",
		pollution: "2021-04-02",
		model: "Maker 9/Model 9",
		insurer_name: "Insurer 9",
		vehicle_color: "Color 9",
		manufacturing_date: "1/9/2018",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "cguvkxc2039",
		pucc_no: "MH09047823",
		puc_expiry: "2016-02-13",
		fit_upto: "2030-12-22",
	},
	{
		license: "NX52DLBR20",
		owner: "Owner 10",
		registration_date: "2021-08-25",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 10",
		owner_count: 2,
		insurance_date: "2010-02-22",
		pollution: "2021-05-29",
		model: "Maker 10/Model 10",
		insurer_name: "Insurer 10",
		vehicle_color: "Color 10",
		manufacturing_date: "1/10/2019",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "okkfjlpll6c",
		pucc_no: "MH06241618",
		puc_expiry: "2022-10-30",
		fit_upto: "2026-05-08",
	},
	{
		license: "KH3LON92QY",
		owner: "Owner 11",
		registration_date: "2019-01-17",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 11",
		owner_count: 5,
		insurance_date: "2019-11-27",
		pollution: "2015-11-29",
		model: "Maker 11/Model 11",
		insurer_name: "Insurer 11",
		vehicle_color: "Color 11",
		manufacturing_date: "1/11/2020",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "xqi6t2hh3bg",
		pucc_no: "MH06705186",
		puc_expiry: "2012-03-10",
		fit_upto: "2028-07-28",
	},
	{
		license: "ZX2WLQHX8Q",
		owner: "Owner 12",
		registration_date: "2021-12-09",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 12",
		owner_count: 1,
		insurance_date: "2017-04-23",
		pollution: "2019-11-04",
		model: "Maker 12/Model 12",
		insurer_name: "Insurer 12",
		vehicle_color: "Color 12",
		manufacturing_date: "1/12/2021",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "l10icbgwo6",
		pucc_no: "MH02079477",
		puc_expiry: "2022-10-09",
		fit_upto: "2031-01-19",
	},
	{
		license: "IO17O3643D",
		owner: "Owner 13",
		registration_date: "2017-05-05",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 13",
		owner_count: 4,
		insurance_date: "2016-09-03",
		pollution: "2014-05-16",
		model: "Maker 13/Model 13",
		insurer_name: "Insurer 13",
		vehicle_color: "Color 13",
		manufacturing_date: "1/13/2022",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "siwiqqz434c",
		pucc_no: "MH03060099",
		puc_expiry: "2019-08-12",
		fit_upto: "2030-02-11",
	},
	{
		license: "KFHM07MM88",
		owner: "Owner 14",
		registration_date: "2010-12-08",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 14",
		owner_count: 5,
		insurance_date: "2010-08-20",
		pollution: "2020-04-14",
		model: "Maker 14/Model 14",
		insurer_name: "Insurer 14",
		vehicle_color: "Color 14",
		manufacturing_date: "1/14/2023",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "etzu9x0oesj",
		pucc_no: "MH02918710",
		puc_expiry: "2019-11-15",
		fit_upto: "2029-09-23",
	},
	{
		license: "LUEVBB0PCM",
		owner: "Owner 15",
		registration_date: "2021-04-11",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 15",
		owner_count: 1,
		insurance_date: "2021-11-01",
		pollution: "2014-11-26",
		model: "Maker 15/Model 15",
		insurer_name: "Insurer 15",
		vehicle_color: "Color 15",
		manufacturing_date: "1/15/2024",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "m2y7rp4dpu",
		pucc_no: "MH04649300",
		puc_expiry: "2014-09-21",
		fit_upto: "2031-10-18",
	},
	{
		license: "XBDF7Y2SON",
		owner: "Owner 16",
		registration_date: "2017-08-13",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 16",
		owner_count: 3,
		insurance_date: "2013-04-07",
		pollution: "2013-02-10",
		model: "Maker 16/Model 16",
		insurer_name: "Insurer 16",
		vehicle_color: "Color 16",
		manufacturing_date: "1/16/2025",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "8mmxl9fqt07",
		pucc_no: "MH08824916",
		puc_expiry: "2018-08-31",
		fit_upto: "2031-02-12",
	},
	{
		license: "CW1SRIFW46",
		owner: "Owner 17",
		registration_date: "2013-01-28",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 17",
		owner_count: 2,
		insurance_date: "2012-11-27",
		pollution: "2012-01-26",
		model: "Maker 17/Model 17",
		insurer_name: "Insurer 17",
		vehicle_color: "Color 17",
		manufacturing_date: "1/17/2026",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "2lvmlhv0hz",
		pucc_no: "MH09927080",
		puc_expiry: "2022-04-30",
		fit_upto: "2025-11-28",
	},
	{
		license: "4B7BSMLFF9",
		owner: "Owner 18",
		registration_date: "2012-08-22",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 18",
		owner_count: 3,
		insurance_date: "2019-09-09",
		pollution: "2012-09-04",
		model: "Maker 18/Model 18",
		insurer_name: "Insurer 18",
		vehicle_color: "Color 18",
		manufacturing_date: "1/18/2027",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "ui5krsp5x5e",
		pucc_no: "MH09785496",
		puc_expiry: "2016-06-20",
		fit_upto: "2028-02-20",
	},
	{
		license: "6TZUQLKA0B",
		owner: "Owner 19",
		registration_date: "2020-03-29",
		fuel_type: "PETROL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 19",
		owner_count: 1,
		insurance_date: "2020-04-01",
		pollution: "2019-05-06",
		model: "Maker 19/Model 19",
		insurer_name: "Insurer 19",
		vehicle_color: "Color 19",
		manufacturing_date: "1/19/2028",
		norms_type: "BHARAT STAGE IV",
		insurance_policy_no: "a1bwiwhc1r",
		pucc_no: "MH0201945",
		puc_expiry: "2010-11-23",
		fit_upto: "2029-12-15",
	},
	{
		license: "2OB5BE6BJ4",
		owner: "Owner 20",
		registration_date: "2014-09-30",
		fuel_type: "DIESEL",
		maker_name: "HONDA MOTORCYCLE AND SCOOTER INDIA (P) LTD",
		maker_model: "Model 20",
		owner_count: 5,
		insurance_date: "2019-12-09",
		pollution: "2011-08-26",
		model: "Maker 20/Model 20",
		insurer_name: "Insurer 20",
		vehicle_color: "Color 20",
		manufacturing_date: "1/20/2029",
		norms_type: "BHARAT STAGE V",
		insurance_policy_no: "7wupps1yd87",
		pucc_no: "MH04023613",
		puc_expiry: "2021-02-26",
		fit_upto: "2029-03-19",
	},
];
export const PLAN_TENURE = [
	{ id: 1, title: "1 Year" },
	{ id: 2, title: "2 Year" },
	{ id: 3, title: "3 Year" },
];

export const PLAN_DATA = [
	{
		id: 1,
		label: "Comprehensive Plan",
		description: [
			"This is the first option description.",
			"Description point 1",
			"Description point 2",
			"Description point 3",
		],
		price: [
			{ id: 1, price: 5000 },
			{ id: 2, price: 8000 },
			{ id: 3, price: 10000 },
		],
	},
	{
		id: 2,
		label: "Third Party Plan",
		description: [
			"This is the second option description.",
			"Description point 1",
			"Description point 2",
		],
		price: [
			{ id: 1, price: 700 },
			{ id: 2, price: 1200 },
			{ id: 3, price: 3000 },
		],
	},
];

export const PERSONAL_ACCIDENT = 350;
/* --------------------------------------------------------- */
